#!/bin/sh
# husky

# Created by Husky v4.3.6 (https://github.com/typicode/husky#readme)
#   At: 1/8/2021, 11:01:26 AM
#   From: /home/matheus/Documents/drive-sync/Projects/Glaros/car-audit/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
